# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tttest20221115',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tttest20221115',
                'lib_path': 'tttest20221115'},
  'syms': {'tttest20221115.core': {'tttest20221115.core.foo': ('core.html#foo', 'tttest20221115/core.py')}}}